// src/data.js

export const USERS = {
  admin: { name: 'Dueño', role: 'admin', avatar: 'DU', password: '1234' },
  seller: { name: 'Vendedor', role: 'seller', avatar: 'VE', password: '4321' },
};

export const INITIAL_MEMBERS = [
  {
    id: '1',
    memberNumber: 1, // Número de Socio Procedural
    name: 'Socio Prueba',
    dni: '12345678', // Campo separado
    phone: '1122334455', // Campo separado
    email: 'socio@test.com',
    extraInfo: 'Socio inicial del sistema',
    points: 50,
    history: [],
  },
];

export const PAYMENT_METHODS = [
  { id: 'Efectivo', label: 'Efectivo' },
  { id: 'MercadoPago', label: 'Mercado Pago' },
  { id: 'Debito', label: 'Débito' },
  { id: 'Credito', label: 'Crédito' },
];

export const INITIAL_CATEGORIES = [
  'Globos',
  'Descartables',
  'Disfraces',
  'Decoración',
  'Velas y Bengalas',
  'Luminoso',
  'Varios',
];

export const INITIAL_INVENTORY = [
  {
    id: 1,
    title: 'Pack Globos Metalizados Dorados',
    brand: 'PartyTime',
    price: 3500,
    purchasePrice: 1800,
    stock: 50,
    category: 'Globos',
    categories: ['Globos'],
    image: 'https://placehold.co/400x400/fbbf24/white?text=Globos',
  },
  {
    id: 2,
    title: 'Set Vasos Neón Fluo (x50)',
    brand: 'Luminix',
    price: 4200,
    purchasePrice: 2100,
    stock: 100,
    category: 'Descartables',
    categories: ['Descartables', 'Luminoso'], // Ejemplo de doble categoría inicial
    image: 'https://placehold.co/400x400/a855f7/white?text=Vasos',
  },
  {
    id: 3,
    title: 'Antifaz Veneciano con Plumas',
    brand: 'CarnavalPro',
    price: 1800,
    purchasePrice: 850,
    stock: 25,
    category: 'Disfraces',
    categories: ['Disfraces'],
    image: '',
  },
  {
    id: 4,
    title: 'Piñata Mexicana Multicolor',
    brand: 'FiestaMex',
    price: 8500,
    purchasePrice: 4000,
    stock: 8,
    category: 'Decoración',
    categories: ['Decoración'],
    image: '',
  },
  {
    id: 5,
    title: 'Bengalas para Torta (Pack x4)',
    brand: 'Chispitas',
    price: 1200,
    purchasePrice: 500,
    stock: 200,
    category: 'Velas y Bengalas',
    categories: ['Velas y Bengalas'],
    image: 'https://placehold.co/400x400/3b82f6/white?text=Bengalas',
  },
  {
    id: 6,
    title: 'Guirnalda LED Multicolor 5m',
    brand: 'Luminix',
    price: 6500,
    purchasePrice: 3200,
    stock: 15,
    category: 'Luminoso',
    categories: ['Luminoso', 'Decoración'],
    image: 'https://placehold.co/400x400/10b981/white?text=LED',
  },
  {
    id: 7,
    title: 'Cotillón Año Nuevo (Kit 10 pers)',
    brand: 'PartyTime',
    price: 12000,
    purchasePrice: 6000,
    stock: 5,
    category: 'Varios',
    categories: ['Varios'],
    image: 'https://placehold.co/400x400/ec4899/white?text=Cotillon',
  },
  {
    id: 8,
    title: 'Velas Número 0-9 Glitter',
    brand: 'Chispitas',
    price: 800,
    purchasePrice: 350,
    stock: 45,
    category: 'Velas y Bengalas',
    categories: ['Velas y Bengalas'],
    image: 'https://placehold.co/400x400/f59e0b/white?text=Velas',
  },
  {
    id: 9,
    title: 'Mantel Descartable Premium',
    brand: 'DecoFiesta',
    price: 2200,
    purchasePrice: 1100,
    stock: 30,
    category: 'Descartables',
    categories: ['Descartables', 'Decoración'],
    image: '',
  },
  {
    id: 10,
    title: 'Peluca Afro Colores',
    brand: 'CarnavalPro',
    price: 3500,
    purchasePrice: 1700,
    stock: 12,
    category: 'Disfraces',
    categories: ['Disfraces'],
    image: 'https://placehold.co/400x400/8b5cf6/white?text=Peluca',
  },
];

// ============================================
// DATOS DE PRUEBA - HISTORIAL REALISTA
// ============================================

const getDateStr = (daysAgo) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toLocaleDateString('es-AR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
};

const getTimeStr = (hour, minute) => {
  return `${hour.toString().padStart(2, '0')}:${minute
    .toString()
    .padStart(2, '0')}`;
};

// Transacciones - MÚLTIPLES POR DÍA (7 días de historial)
export const INITIAL_TRANSACTIONS = [
  // ========== HOY (día 0) - 12 transacciones ==========
  {
    id: 1001,
    date: getDateStr(0),
    time: getTimeStr(9, 15),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 3 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 12900,
    status: 'completed',
  },
  {
    id: 1002,
    date: getDateStr(0),
    time: getTimeStr(9, 45),
    user: 'Vendedor',
    items: [{ id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 3 }],
    payment: 'Efectivo',
    total: 2400,
    status: 'completed',
  },
  {
    id: 1003,
    date: getDateStr(0),
    time: getTimeStr(10, 30),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 1 },
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 2 },
    ],
    payment: 'MercadoPago',
    total: 8100,
    status: 'completed',
  },
  {
    id: 1004,
    date: getDateStr(0),
    time: getTimeStr(11, 15),
    user: 'Dueño',
    items: [
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 2 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 12800,
    status: 'completed',
  },
  {
    id: 1005,
    date: getDateStr(0),
    time: getTimeStr(12, 0),
    user: 'Vendedor',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
    ],
    payment: 'Debito',
    total: 8500,
    status: 'completed',
  },
  {
    id: 1006,
    date: getDateStr(0),
    time: getTimeStr(13, 30),
    user: 'Vendedor',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 2,
      },
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 3 },
    ],
    payment: 'Credito',
    total: 39820,
    status: 'completed',
  },
  {
    id: 1007,
    date: getDateStr(0),
    time: getTimeStr(14, 20),
    user: 'Vendedor',
    items: [
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 4 },
    ],
    payment: 'Efectivo',
    total: 7200,
    status: 'completed',
  },
  {
    id: 1008,
    date: getDateStr(0),
    time: getTimeStr(15, 45),
    user: 'Dueño',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 2 },
    ],
    payment: 'Debito',
    total: 15500,
    status: 'completed',
  },
  {
    id: 1009,
    date: getDateStr(0),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 2 },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 3 },
    ],
    payment: 'MercadoPago',
    total: 12400,
    status: 'completed',
  },
  {
    id: 1010,
    date: getDateStr(0),
    time: getTimeStr(17, 10),
    user: 'Vendedor',
    items: [
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 5 },
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 4 },
    ],
    payment: 'Efectivo',
    total: 9200,
    status: 'completed',
  },
  {
    id: 1011,
    date: getDateStr(0),
    time: getTimeStr(18, 0),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 2 },
    ],
    payment: 'Credito',
    total: 14300,
    status: 'completed',
  },
  {
    id: 1012,
    date: getDateStr(0),
    time: getTimeStr(18, 45),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 3 },
    ],
    payment: 'Efectivo',
    total: 18600,
    status: 'completed',
  },

  // ========== AYER (día 1) - 10 transacciones ==========
  {
    id: 2001,
    date: getDateStr(1),
    time: getTimeStr(9, 30),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 5 },
    ],
    payment: 'Efectivo',
    total: 17500,
    status: 'completed',
  },
  {
    id: 2002,
    date: getDateStr(1),
    time: getTimeStr(10, 15),
    user: 'Vendedor',
    items: [
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 6 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 3 },
    ],
    payment: 'MercadoPago',
    total: 8400,
    status: 'completed',
  },
  {
    id: 2003,
    date: getDateStr(1),
    time: getTimeStr(11, 0),
    user: 'Dueño',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 2 },
    ],
    payment: 'Debito',
    total: 17000,
    status: 'completed',
  },
  {
    id: 2004,
    date: getDateStr(1),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 4 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 4 },
    ],
    payment: 'Efectivo',
    total: 25600,
    status: 'completed',
  },
  {
    id: 2005,
    date: getDateStr(1),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 1 },
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 1 },
    ],
    payment: 'Credito',
    total: 11000,
    status: 'completed',
  },
  {
    id: 2006,
    date: getDateStr(1),
    time: getTimeStr(14, 30),
    user: 'Vendedor',
    items: [
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 8 },
    ],
    payment: 'Efectivo',
    total: 14400,
    status: 'completed',
  },
  {
    id: 2007,
    date: getDateStr(1),
    time: getTimeStr(15, 45),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
    ],
    payment: 'MercadoPago',
    total: 12000,
    status: 'completed',
  },
  {
    id: 2008,
    date: getDateStr(1),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 2 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 4 },
    ],
    payment: 'Debito',
    total: 11800,
    status: 'completed',
  },
  {
    id: 2009,
    date: getDateStr(1),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [{ id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 5 }],
    payment: 'Efectivo',
    total: 4000,
    status: 'completed',
  },
  {
    id: 2010,
    date: getDateStr(1),
    time: getTimeStr(18, 30),
    user: 'Vendedor',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 2 },
    ],
    payment: 'Credito',
    total: 18590,
    status: 'completed',
  },

  // ========== Hace 2 días - 10 transacciones ==========
  {
    id: 3001,
    date: getDateStr(2),
    time: getTimeStr(9, 20),
    user: 'Vendedor',
    items: [
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 10 },
    ],
    payment: 'Efectivo',
    total: 12000,
    status: 'completed',
  },
  {
    id: 3002,
    date: getDateStr(2),
    time: getTimeStr(10, 0),
    user: 'Dueño',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 3 },
    ],
    payment: 'MercadoPago',
    total: 19500,
    status: 'completed',
  },
  {
    id: 3003,
    date: getDateStr(2),
    time: getTimeStr(11, 15),
    user: 'Vendedor',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 2,
      },
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 4 },
    ],
    payment: 'Credito',
    total: 41800,
    status: 'completed',
  },
  {
    id: 3004,
    date: getDateStr(2),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 6 },
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 17800,
    status: 'completed',
  },
  {
    id: 3005,
    date: getDateStr(2),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [{ id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 8 }],
    payment: 'Debito',
    total: 6400,
    status: 'completed',
  },
  {
    id: 3006,
    date: getDateStr(2),
    time: getTimeStr(14, 30),
    user: 'Dueño',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 5 },
    ],
    payment: 'Efectivo',
    total: 19500,
    status: 'completed',
  },
  {
    id: 3007,
    date: getDateStr(2),
    time: getTimeStr(15, 45),
    user: 'Vendedor',
    items: [{ id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 3 }],
    payment: 'MercadoPago',
    total: 12600,
    status: 'completed',
  },
  {
    id: 3008,
    date: getDateStr(2),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 3 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 12900,
    status: 'completed',
  },
  {
    id: 3009,
    date: getDateStr(2),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 1 },
    ],
    payment: 'Credito',
    total: 7150,
    status: 'completed',
  },
  {
    id: 3010,
    date: getDateStr(2),
    time: getTimeStr(18, 30),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 4 },
    ],
    payment: 'Debito',
    total: 19200,
    status: 'completed',
  },

  // ========== Hace 3 días - 10 transacciones ==========
  {
    id: 4001,
    date: getDateStr(3),
    time: getTimeStr(9, 30),
    user: 'Vendedor',
    items: [
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 10 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 5 },
    ],
    payment: 'Efectivo',
    total: 14000,
    status: 'completed',
  },
  {
    id: 4002,
    date: getDateStr(3),
    time: getTimeStr(10, 15),
    user: 'Vendedor',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 2 },
    ],
    payment: 'MercadoPago',
    total: 17000,
    status: 'completed',
  },
  {
    id: 4003,
    date: getDateStr(3),
    time: getTimeStr(11, 0),
    user: 'Dueño',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 6 },
    ],
    payment: 'Efectivo',
    total: 21000,
    status: 'completed',
  },
  {
    id: 4004,
    date: getDateStr(3),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 5 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 5 },
    ],
    payment: 'Credito',
    total: 35200,
    status: 'completed',
  },
  {
    id: 4005,
    date: getDateStr(3),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 3 },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 6 },
    ],
    payment: 'Debito',
    total: 21300,
    status: 'completed',
  },
  {
    id: 4006,
    date: getDateStr(3),
    time: getTimeStr(14, 30),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 13000,
    status: 'completed',
  },
  {
    id: 4007,
    date: getDateStr(3),
    time: getTimeStr(15, 45),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 3 },
    ],
    payment: 'MercadoPago',
    total: 15600,
    status: 'completed',
  },
  {
    id: 4008,
    date: getDateStr(3),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [{ id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 4 }],
    payment: 'Efectivo',
    total: 3200,
    status: 'completed',
  },
  {
    id: 4009,
    date: getDateStr(3),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 2 },
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
    ],
    payment: 'Credito',
    total: 17050,
    status: 'completed',
  },
  {
    id: 4010,
    date: getDateStr(3),
    time: getTimeStr(18, 30),
    user: 'Vendedor',
    items: [
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 2 },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 3 },
    ],
    payment: 'Debito',
    total: 13800,
    status: 'completed',
  },

  // ========== Hace 4 días - 10 transacciones ==========
  {
    id: 5001,
    date: getDateStr(4),
    time: getTimeStr(9, 15),
    user: 'Vendedor',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 3,
      },
    ],
    payment: 'Efectivo',
    total: 36000,
    status: 'completed',
  },
  {
    id: 5002,
    date: getDateStr(4),
    time: getTimeStr(10, 0),
    user: 'Dueño',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 4 },
    ],
    payment: 'MercadoPago',
    total: 26000,
    status: 'completed',
  },
  {
    id: 5003,
    date: getDateStr(4),
    time: getTimeStr(11, 15),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 4 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 6 },
    ],
    payment: 'Efectivo',
    total: 21200,
    status: 'completed',
  },
  {
    id: 5004,
    date: getDateStr(4),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [{ id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 12 }],
    payment: 'Debito',
    total: 9600,
    status: 'completed',
  },
  {
    id: 5005,
    date: getDateStr(4),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 4 },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 8 },
    ],
    payment: 'Credito',
    total: 31240,
    status: 'completed',
  },
  {
    id: 5006,
    date: getDateStr(4),
    time: getTimeStr(14, 30),
    user: 'Dueño',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 2 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 3 },
    ],
    payment: 'Efectivo',
    total: 23600,
    status: 'completed',
  },
  {
    id: 5007,
    date: getDateStr(4),
    time: getTimeStr(15, 45),
    user: 'Vendedor',
    items: [{ id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 3 }],
    payment: 'MercadoPago',
    total: 12600,
    status: 'completed',
  },
  {
    id: 5008,
    date: getDateStr(4),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 2 },
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 1 },
    ],
    payment: 'Efectivo',
    total: 13500,
    status: 'completed',
  },
  {
    id: 5009,
    date: getDateStr(4),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 8 },
    ],
    payment: 'Debito',
    total: 9600,
    status: 'completed',
  },
  {
    id: 5010,
    date: getDateStr(4),
    time: getTimeStr(18, 30),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
    ],
    payment: 'Credito',
    total: 13200,
    status: 'completed',
  },

  // ========== Hace 5 días - 10 transacciones ==========
  {
    id: 6001,
    date: getDateStr(5),
    time: getTimeStr(9, 30),
    user: 'Vendedor',
    items: [
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 10 },
    ],
    payment: 'Efectivo',
    total: 18000,
    status: 'completed',
  },
  {
    id: 6002,
    date: getDateStr(5),
    time: getTimeStr(10, 15),
    user: 'Vendedor',
    items: [
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 3 },
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 3 },
    ],
    payment: 'MercadoPago',
    total: 21000,
    status: 'completed',
  },
  {
    id: 6003,
    date: getDateStr(5),
    time: getTimeStr(11, 0),
    user: 'Dueño',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 3 },
    ],
    payment: 'Debito',
    total: 25500,
    status: 'completed',
  },
  {
    id: 6004,
    date: getDateStr(5),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 15 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 8 },
    ],
    payment: 'Efectivo',
    total: 21600,
    status: 'completed',
  },
  {
    id: 6005,
    date: getDateStr(5),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 2 },
    ],
    payment: 'Credito',
    total: 14300,
    status: 'completed',
  },
  {
    id: 6006,
    date: getDateStr(5),
    time: getTimeStr(14, 30),
    user: 'Vendedor',
    items: [
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 4 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 4 },
    ],
    payment: 'Efectivo',
    total: 25600,
    status: 'completed',
  },
  {
    id: 6007,
    date: getDateStr(5),
    time: getTimeStr(15, 45),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 2,
      },
    ],
    payment: 'MercadoPago',
    total: 24000,
    status: 'completed',
  },
  {
    id: 6008,
    date: getDateStr(5),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 5 },
    ],
    payment: 'Debito',
    total: 17500,
    status: 'completed',
  },
  {
    id: 6009,
    date: getDateStr(5),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 5 },
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 2 },
    ],
    payment: 'Efectivo',
    total: 16000,
    status: 'completed',
  },
  {
    id: 6010,
    date: getDateStr(5),
    time: getTimeStr(18, 30),
    user: 'Vendedor',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 1 },
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 4 },
    ],
    payment: 'Credito',
    total: 14190,
    status: 'completed',
  },

  // ========== Hace 6 días - 10 transacciones ==========
  {
    id: 7001,
    date: getDateStr(6),
    time: getTimeStr(9, 15),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 3 },
    ],
    payment: 'Efectivo',
    total: 19500,
    status: 'completed',
  },
  {
    id: 7002,
    date: getDateStr(6),
    time: getTimeStr(10, 0),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 2,
      },
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 10 },
    ],
    payment: 'MercadoPago',
    total: 32000,
    status: 'completed',
  },
  {
    id: 7003,
    date: getDateStr(6),
    time: getTimeStr(11, 15),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 6 },
    ],
    payment: 'Debito',
    total: 21000,
    status: 'completed',
  },
  {
    id: 7004,
    date: getDateStr(6),
    time: getTimeStr(12, 30),
    user: 'Vendedor',
    items: [
      { id: 4, title: 'Piñata Mexicana Multicolor', price: 8500, qty: 2 },
      { id: 9, title: 'Mantel Descartable Premium', price: 2200, qty: 6 },
    ],
    payment: 'Efectivo',
    total: 30200,
    status: 'completed',
  },
  {
    id: 7005,
    date: getDateStr(6),
    time: getTimeStr(13, 45),
    user: 'Vendedor',
    items: [{ id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 5 }],
    payment: 'Credito',
    total: 23100,
    status: 'completed',
  },
  {
    id: 7006,
    date: getDateStr(6),
    time: getTimeStr(14, 30),
    user: 'Dueño',
    items: [
      { id: 5, title: 'Bengalas para Torta (Pack x4)', price: 1200, qty: 10 },
    ],
    payment: 'Efectivo',
    total: 12000,
    status: 'completed',
  },
  {
    id: 7007,
    date: getDateStr(6),
    time: getTimeStr(15, 45),
    user: 'Vendedor',
    items: [
      { id: 10, title: 'Peluca Afro Colores', price: 3500, qty: 4 },
      { id: 3, title: 'Antifaz Veneciano con Plumas', price: 1800, qty: 5 },
    ],
    payment: 'MercadoPago',
    total: 23000,
    status: 'completed',
  },
  {
    id: 7008,
    date: getDateStr(6),
    time: getTimeStr(16, 30),
    user: 'Vendedor',
    items: [
      { id: 6, title: 'Guirnalda LED Multicolor 5m', price: 6500, qty: 1 },
      { id: 8, title: 'Velas Número 0-9 Glitter', price: 800, qty: 5 },
    ],
    payment: 'Debito',
    total: 10500,
    status: 'completed',
  },
  {
    id: 7009,
    date: getDateStr(6),
    time: getTimeStr(17, 45),
    user: 'Vendedor',
    items: [
      { id: 1, title: 'Pack Globos Metalizados Dorados', price: 3500, qty: 3 },
    ],
    payment: 'Efectivo',
    total: 10500,
    status: 'completed',
  },
  {
    id: 7010,
    date: getDateStr(6),
    time: getTimeStr(18, 30),
    user: 'Dueño',
    items: [
      {
        id: 7,
        title: 'Cotillón Año Nuevo (Kit 10 pers)',
        price: 12000,
        qty: 1,
      },
      { id: 2, title: 'Set Vasos Neón Fluo (x50)', price: 4200, qty: 2 },
    ],
    payment: 'Credito',
    total: 22440,
    status: 'completed',
  },
];

// Logs con historial completo
export const INITIAL_LOGS = [
  // ========== Hace 6 días ==========
  {
    id: 1,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(6),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 20000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 2,
    timestamp: getTimeStr(10, 30),
    date: getDateStr(6),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 901,
      items: [
        { title: 'Pack Globos Metalizados Dorados', qty: 5, price: 3500 },
        { title: 'Bengalas para Torta (Pack x4)', qty: 3, price: 1200 },
      ],
      total: 21100,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 3,
    timestamp: getTimeStr(15, 45),
    date: getDateStr(6),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 902,
      items: [{ title: 'Piñata Mexicana Multicolor', qty: 2, price: 8500 }],
      total: 17000,
      payment: 'MercadoPago',
    },
    reason: '',
  },
  {
    id: 4,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(6),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 2,
      totalSales: 38100,
      openingBalance: 20000,
      finalBalance: 58100,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== Hace 5 días ==========
  {
    id: 5,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(5),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 25000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 6,
    timestamp: getTimeStr(11, 20),
    date: getDateStr(5),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 903,
      items: [
        { title: 'Guirnalda LED Multicolor 5m', qty: 3, price: 6500 },
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 1, price: 12000 },
      ],
      total: 31500,
      payment: 'Credito',
    },
    reason: '',
  },
  {
    id: 7,
    timestamp: getTimeStr(13, 15),
    date: getDateStr(5),
    action: 'Alta de Producto',
    user: 'Dueño',
    details: {
      id: 11,
      title: 'Confeti Metalizado 500g',
      brand: 'PartyTime',
      price: 1500,
      purchasePrice: 700,
      stock: 40,
      category: 'Decoración',
    },
    reason: 'Producto Nuevo',
  },
  {
    id: 8,
    timestamp: getTimeStr(16, 30),
    date: getDateStr(5),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 904,
      items: [
        { title: 'Set Vasos Neón Fluo (x50)', qty: 4, price: 4200 },
        { title: 'Mantel Descartable Premium', qty: 4, price: 2200 },
      ],
      total: 25600,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 9,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(5),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 2,
      totalSales: 57100,
      openingBalance: 25000,
      finalBalance: 82100,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== Hace 4 días ==========
  {
    id: 10,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(4),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 30000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 11,
    timestamp: getTimeStr(10, 45),
    date: getDateStr(4),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 905,
      items: [
        { title: 'Peluca Afro Colores', qty: 3, price: 3500 },
        { title: 'Antifaz Veneciano con Plumas', qty: 6, price: 1800 },
      ],
      total: 21300,
      payment: 'Debito',
    },
    reason: '',
  },
  {
    id: 12,
    timestamp: getTimeStr(12, 30),
    date: getDateStr(4),
    action: 'Edición Producto',
    user: 'Dueño',
    details: {
      product: 'Bengalas para Torta (Pack x4)',
      changes: {
        price: { old: 1000, new: 1200 },
        stock: { old: 180, new: 200 },
      },
    },
    reason: 'Ajuste por inflación y reposición de stock',
  },
  {
    id: 13,
    timestamp: getTimeStr(14, 20),
    date: getDateStr(4),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 906,
      items: [
        { title: 'Pack Globos Metalizados Dorados', qty: 8, price: 3500 },
      ],
      total: 28000,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 14,
    timestamp: getTimeStr(17, 0),
    date: getDateStr(4),
    action: 'Venta Anulada',
    user: 'Dueño',
    details: {
      transactionId: 906,
      originalTotal: 28000,
      itemsReturned: [{ title: 'Pack Globos Metalizados Dorados', qty: 8 }],
    },
    reason: 'Cliente cambió de opinión, devolvió todo',
  },
  {
    id: 15,
    timestamp: getTimeStr(18, 30),
    date: getDateStr(4),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 907,
      items: [
        { title: 'Velas Número 0-9 Glitter', qty: 10, price: 800 },
        { title: 'Bengalas para Torta (Pack x4)', qty: 5, price: 1200 },
      ],
      total: 14000,
      payment: 'MercadoPago',
    },
    reason: '',
  },
  {
    id: 16,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(4),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 2,
      totalSales: 35300,
      openingBalance: 30000,
      finalBalance: 65300,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== Hace 3 días ==========
  {
    id: 17,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(3),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 25000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 18,
    timestamp: getTimeStr(10, 0),
    date: getDateStr(3),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 908,
      items: [
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 3, price: 12000 },
      ],
      total: 36000,
      payment: 'Credito',
    },
    reason: '',
  },
  {
    id: 19,
    timestamp: getTimeStr(12, 45),
    date: getDateStr(3),
    action: 'Modificación Pedido',
    user: 'Dueño',
    details: {
      transactionId: 908,
      changes: {
        total: { old: 36000, new: 26400 },
      },
      productChanges: [
        {
          title: 'Cotillón Año Nuevo (Kit 10 pers)',
          oldQty: 3,
          newQty: 2,
          diff: -1,
        },
      ],
      itemsSnapshot: [
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 2, price: 12000 },
      ],
    },
    reason: 'Cliente solo necesitaba 2 kits, error al cargar',
  },
  {
    id: 20,
    timestamp: getTimeStr(15, 30),
    date: getDateStr(3),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 909,
      items: [
        { title: 'Piñata Mexicana Multicolor', qty: 1, price: 8500 },
        { title: 'Pack Globos Metalizados Dorados', qty: 4, price: 3500 },
        { title: 'Velas Número 0-9 Glitter', qty: 2, price: 800 },
      ],
      total: 24100,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 21,
    timestamp: getTimeStr(18, 15),
    date: getDateStr(3),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 910,
      items: [{ title: 'Guirnalda LED Multicolor 5m', qty: 2, price: 6500 }],
      total: 13000,
      payment: 'Debito',
    },
    reason: '',
  },
  {
    id: 22,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(3),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 3,
      totalSales: 63500,
      openingBalance: 25000,
      finalBalance: 88500,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== Hace 2 días ==========
  {
    id: 23,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(2),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 28000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 24,
    timestamp: getTimeStr(11, 30),
    date: getDateStr(2),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 911,
      items: [
        { title: 'Set Vasos Neón Fluo (x50)', qty: 5, price: 4200 },
        { title: 'Mantel Descartable Premium', qty: 5, price: 2200 },
      ],
      total: 32000,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 25,
    timestamp: getTimeStr(14, 0),
    date: getDateStr(2),
    action: 'Edición Producto',
    user: 'Dueño',
    details: {
      product: 'Piñata Mexicana Multicolor',
      changes: {
        price: { old: 7500, new: 8500 },
      },
    },
    reason: 'Actualización de precio por costo de proveedor',
  },
  {
    id: 26,
    timestamp: getTimeStr(16, 45),
    date: getDateStr(2),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 912,
      items: [
        { title: 'Antifaz Veneciano con Plumas', qty: 10, price: 1800 },
        { title: 'Peluca Afro Colores', qty: 4, price: 3500 },
      ],
      total: 32000,
      payment: 'MercadoPago',
    },
    reason: '',
  },
  {
    id: 27,
    timestamp: getTimeStr(17, 30),
    date: getDateStr(2),
    action: 'Modificación Pedido',
    user: 'Dueño',
    details: {
      transactionId: 912,
      changes: {
        total: { old: 32000, new: 35500 },
      },
      productChanges: [
        {
          title: 'Antifaz Veneciano con Plumas',
          oldQty: 10,
          newQty: 10,
          diff: 0,
        },
        { title: 'Peluca Afro Colores', oldQty: 4, newQty: 4, diff: 0 },
        {
          title: 'Pack Globos Metalizados Dorados',
          oldQty: 0,
          newQty: 1,
          diff: 1,
        },
      ],
      itemsSnapshot: [
        { title: 'Antifaz Veneciano con Plumas', qty: 10, price: 1800 },
        { title: 'Peluca Afro Colores', qty: 4, price: 3500 },
        { title: 'Pack Globos Metalizados Dorados', qty: 1, price: 3500 },
      ],
    },
    reason: 'Cliente pidió agregar globos a último momento',
  },
  {
    id: 28,
    timestamp: getTimeStr(19, 30),
    date: getDateStr(2),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 913,
      items: [{ title: 'Bengalas para Torta (Pack x4)', qty: 8, price: 1200 }],
      total: 9600,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 29,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(2),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 3,
      totalSales: 77100,
      openingBalance: 28000,
      finalBalance: 105100,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== Ayer ==========
  {
    id: 30,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(1),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 30000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 31,
    timestamp: getTimeStr(10, 15),
    date: getDateStr(1),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 914,
      items: [
        { title: 'Pack Globos Metalizados Dorados', qty: 6, price: 3500 },
        { title: 'Guirnalda LED Multicolor 5m', qty: 2, price: 6500 },
      ],
      total: 34000,
      payment: 'Debito',
    },
    reason: '',
  },
  {
    id: 32,
    timestamp: getTimeStr(11, 0),
    date: getDateStr(1),
    action: 'Edición Producto',
    user: 'Dueño',
    details: {
      product: 'Set Vasos Neón Fluo (x50)',
      changes: {
        price: { old: 3800, new: 4200 },
        purchasePrice: { old: 1900, new: 2100 },
        stock: { old: 85, new: 100 },
      },
    },
    reason: 'Reposición de stock y ajuste de precios',
  },
  {
    id: 33,
    timestamp: getTimeStr(12, 0),
    date: getDateStr(1),
    action: 'Categoría',
    user: 'Dueño',
    details: { name: 'Temáticos', type: 'create' },
    reason: 'Nueva categoría para productos temáticos',
  },
  {
    id: 34,
    timestamp: getTimeStr(13, 30),
    date: getDateStr(1),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 915,
      items: [
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 2, price: 12000 },
        { title: 'Velas Número 0-9 Glitter', qty: 5, price: 800 },
      ],
      total: 28000,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 35,
    timestamp: getTimeStr(14, 15),
    date: getDateStr(1),
    action: 'Modificación Pedido',
    user: 'Dueño',
    details: {
      transactionId: 915,
      changes: {
        payment: { old: 'Efectivo', new: 'MercadoPago' },
      },
      productChanges: [],
      itemsSnapshot: [
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 2, price: 12000 },
        { title: 'Velas Número 0-9 Glitter', qty: 5, price: 800 },
      ],
    },
    reason: 'Cliente prefirió pagar con MercadoPago',
  },
  {
    id: 36,
    timestamp: getTimeStr(16, 0),
    date: getDateStr(1),
    action: 'Venta Realizada',
    user: 'Dueño',
    details: {
      transactionId: 916,
      items: [{ title: 'Piñata Mexicana Multicolor', qty: 2, price: 8500 }],
      total: 17000,
      payment: 'Credito',
    },
    reason: '',
  },
  {
    id: 37,
    timestamp: getTimeStr(18, 45),
    date: getDateStr(1),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 917,
      items: [
        { title: 'Set Vasos Neón Fluo (x50)', qty: 3, price: 4200 },
        { title: 'Bengalas para Torta (Pack x4)', qty: 4, price: 1200 },
      ],
      total: 17400,
      payment: 'MercadoPago',
    },
    reason: '',
  },
  {
    id: 38,
    timestamp: getTimeStr(21, 0),
    date: getDateStr(1),
    action: 'Cierre de Caja',
    user: 'Dueño',
    details: {
      salesCount: 4,
      totalSales: 96400,
      openingBalance: 30000,
      finalBalance: 126400,
      closingTime: '21:00',
      scheduledClosingTime: '21:00',
    },
    reason: 'Cierre de jornada',
  },

  // ========== HOY ==========
  {
    id: 39,
    timestamp: getTimeStr(9, 0),
    date: getDateStr(0),
    action: 'Apertura de Caja',
    user: 'Dueño',
    details: { amount: 25000, scheduledClosingTime: '21:00' },
    reason: 'Inicio de operaciones',
  },
  {
    id: 40,
    timestamp: getTimeStr(10, 15),
    date: getDateStr(0),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 1001,
      items: [
        { title: 'Pack Globos Metalizados Dorados', qty: 3, price: 3500 },
        { title: 'Bengalas para Torta (Pack x4)', qty: 2, price: 1200 },
      ],
      total: 12900,
      payment: 'Efectivo',
    },
    reason: '',
  },
  {
    id: 41,
    timestamp: getTimeStr(11, 30),
    date: getDateStr(0),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 1002,
      items: [
        { title: 'Guirnalda LED Multicolor 5m', qty: 1, price: 6500 },
        { title: 'Velas Número 0-9 Glitter', qty: 2, price: 800 },
      ],
      total: 8100,
      payment: 'MercadoPago',
    },
    reason: '',
  },
  {
    id: 42,
    timestamp: getTimeStr(13, 0),
    date: getDateStr(0),
    action: 'Edición Producto',
    user: 'Dueño',
    details: {
      product: 'Cotillón Año Nuevo (Kit 10 pers)',
      changes: {
        stock: { old: 8, new: 5 },
      },
    },
    reason: 'Corrección de inventario físico',
  },
  {
    id: 43,
    timestamp: getTimeStr(14, 45),
    date: getDateStr(0),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 1003,
      items: [
        { title: 'Cotillón Año Nuevo (Kit 10 pers)', qty: 2, price: 12000 },
        { title: 'Set Vasos Neón Fluo (x50)', qty: 3, price: 4200 },
      ],
      total: 39820,
      payment: 'Credito',
    },
    reason: '',
  },
  {
    id: 44,
    timestamp: getTimeStr(16, 20),
    date: getDateStr(0),
    action: 'Venta Realizada',
    user: 'Dueño',
    details: {
      transactionId: 1004,
      items: [
        { title: 'Piñata Mexicana Multicolor', qty: 1, price: 8500 },
        { title: 'Pack Globos Metalizados Dorados', qty: 2, price: 3500 },
      ],
      total: 15500,
      payment: 'Debito',
    },
    reason: '',
  },
  {
    id: 45,
    timestamp: getTimeStr(17, 10),
    date: getDateStr(0),
    action: 'Venta Realizada',
    user: 'Vendedor',
    details: {
      transactionId: 1005,
      items: [
        { title: 'Antifaz Veneciano con Plumas', qty: 5, price: 1800 },
        { title: 'Peluca Afro Colores', qty: 2, price: 3500 },
      ],
      total: 16000,
      payment: 'Efectivo',
    },
    reason: '',
  },
];

export const COLORS = [
  '#f472b6',
  '#a78bfa',
  '#60a5fa',
  '#34d399',
  '#fbbf24',
  '#f87171',
  '#2dd4bf',
  '#818cf8',
];

export const getColorForItem = (id) => COLORS[id % COLORS.length];

export const getInitialState = (key, initialValue) => {
  try {
    const item = window.localStorage.getItem(key);
    return item ? JSON.parse(item) : initialValue;
  } catch (error) {
    console.error('Error cargando localStorage', error);
    return initialValue;
  }
};